### ISSUE TITLE
I need help of shift mcu

### ISSUE THREAD

**Issue by DRCRecoveryData** [ImageProcessing-ElectronicPublications/jpegrepair#1]
Can you help me to fix code of my issue?

https://github.com/albmac/JPEGVisualRepairTool/discussions/14#discussioncomment-9222556

**Comment by zvezdochiot** [comment]
@DRCRecoveryData , see [jpeg-decomp](https://github.com/ImageProcessing-ElectronicPublications/jpeg-decomp).

**Comment by DRCRecoveryData** [comment]
> @DRCRecoveryData , see [jpeg-decomp](https://github.com/ImageProcessing-ElectronicPublications/jpeg-decomp).
> 

My pyqt6 gui code is wrong when shift mcu could you check it?
